# Generated by Django 4.2.2 on 2023-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsstory_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsstory",
            name="img_url",
            field=models.URLField(
                default="https://cdn.vox-cdn.com/thumbor/WR9hE8wvdM4hfHysXitls9_bCZI=/0x0:1192x795/1400x1400/filters:focal(596x398:597x399)/cdn.vox-cdn.com/uploads/chorus_asset/file/22312759/rickroll_4k.jpg"
            ),
        ),
    ]
