# Generated by Django 4.2.2 on 2023-07-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_img_url_newsstory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsstory",
            name="image",
            field=models.URLField(
                default="https://www.pngmart.com/image/159906/png/159905"
            ),
        ),
    ]
